[package]
name = "bee-ternary-demo"
version = "0.1.0"
authors = ["huhn511 <huhn@einfachIOTA.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bee-ternary = "0.1.0-alpha"